### ISSUE TITLE
dymask_list为空

### ISSUE THREAD

**Issue by nono666** [zju3dv/PVO#11]
Traceback (most recent call last):
  File "/mnt/share_disk/lvnuo/LN/code/pvo/VO_Module/evaluation_scripts/test_vo2.py", line 93, in <module>
    for i_batch, item in enumerate(train_loader):
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/envs/pvoenv/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/mnt/share_disk/lvnuo/LN/code/pvo/VO_Module/droid_slam/data_readers/base.py", line 189, in __getitem__
    mask, v = self.__class__.dymask_read(dymask_list[i])
IndexError: list index out of range

我在运行test_vo_scene.sh时报如下的错误，请帮帮我

**Comment by nuko7055** [comment]
Hi,
 
The reason why the dynamic mask list is empty is the "generate_dynamic_masks.py" (tools/datasets/generate_dynamic_masks.py) only inference the mask for "clone" which is for training. The 15-deg-left (using in testing) doesn't inference. This is my simple debug log for the github repo. Hope it helps you.

https://hackmd.io/@neko7055/HJCTkx7U6

**Comment by 110sha** [comment]
@nuko7055 Your link cannot be opened. What is the solution?

**Comment by nuko7055** [comment]
> @nuko7055 Your link cannot be opened. What is the solution?

I modified tools/datasets/generate_dynamic_masks.py to look like the following.
![image](https://github.com/zju3dv/PVO/assets/145477948/bb1e0986-bd81-4b75-9b7b-31a1d0481710)

**Comment by nuko7055** [comment]
By the way, VO_Module/droid_slam/data_readers/vkitti2.py loads the dynamic mask with wrong path. You also need to modify it to look like the following.

From
![image](https://github.com/zju3dv/PVO/assets/145477948/cef87569-9221-4d76-899b-076279080080)
To
![image](https://github.com/zju3dv/PVO/assets/145477948/5ce237f7-cf70-4185-99b4-cf95658ca50a)

**Comment by 110sha** [comment]
@nuko7055 Thank you very much for providing the solution, it's very useful!
